events {
    worker_connections 1024;
}

http {
    upstream api_backend {
        server api-server:8000;
    }
    
    upstream route_backend {
        server route-service:8001;
    }
    
    upstream drone_backend {
        server drone-service:8002;
    }
    
    upstream order_backend {
        server order-service:8003;
    }

    server {
        listen 80;
        
        # API сервер
        location / {
            proxy_pass http://api_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        # Сервис маршрутов
        location /route/ {
            rewrite ^/route/(.*) /$1 break;
            proxy_pass http://route_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        # Сервис дронов
        location /drone/ {
            rewrite ^/drone/(.*) /$1 break;
            proxy_pass http://drone_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        # Сервис заказов
        location /order/ {
            rewrite ^/order/(.*) /$1 break;
            proxy_pass http://order_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}

